### ISSUE TITLE
An unhandled exception of type 'System.NullReferenceException' occurred in xZune.Vlc.Wpf.dll

### ISSUE THREAD

**Issue by Evilpaule** [higankanshi/Meta.Vlc#107]
i got An unhandled exception of type 'System.NullReferenceException' occurred in xZune.Vlc.Wpf.dll
Additional information: Object reference not set to an instance of an object.

All libs are in the folder and checked.

**Comment by higankanshi** [comment]
Can you give more information? like: stack trace...

**Comment by Evilpaule** [comment]
Sorry but i cant get more information than this:

http://prntscr.com/aownpy

The thread stops on this: 
Not Flagged	>	12280	40	Worker Thread	<No Name>	xZune.Vlc.Wpf.dll!xZune.Vlc.Wpf.VlcPlayer.VideoFormatCallback	Above Normal
 	 	 	 	 	 	[External Code]	 
and in console this:
[0bce7de4] avi demux error: no key frame set for track 0
[0bce7de4] avi demux error: no key frame set for track 1
[0bce7de4] avi demux error: no key frame set for track 0
[0bce7de4] avi demux error: no key frame set for track 1

**Comment by higankanshi** [comment]
If you check the exception object, you can get stack trace information.

**Comment by Evilpaule** [comment]
Sorry but as you can see in the link http://prntscr.com/aownpy
i cant go to object details and see the stacktrace

**Comment by higankanshi** [comment]
I need stack trace information to identify the issue.
Stack trace information like this (#110):
```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at xZune.Vlc.Wpf.ThreadSeparatedImage.LoadThreadSeparatedControl()
   at xZune.Vlc.Wpf.ThreadSeparatedControlHost.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
```

**Comment by Transigent** [comment]
Hi first of all thanks very much for your efforts on this project. Regrettably I am having the same trouble as mentioned by the OP.

I can consistently replicate this problem by opening the attached video file, which is one that ships with Windows 7, in C:\Program Files\Common Files\Microsoft Shared\ink\en-US, called join.avi

1. To replicate, run the sample project.
2. Click Load, and open the attached video file.
3. Then click Load again and open the same file. The player hangs and I get the following message: 
"**An unhandled exception of type 'System.AccessViolationException' occurred in xZune.Vlc.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."**

The hang happens when you open a different file first, then join.avi too.

I have tried framework 4.5 and 4.0 versions, same problem. I have also tried various VLC versions, the current is 2.2.2. I am building for x86. If I try to play the file in the actual VLC player application, it plays normally. I have tried transplanting your control into a VB application harness as well, same result.

[TestFile.zip](https://github.com/higankanshi/xZune.Vlc/files/215250/TestFile.zip)

Thanks for any assistance! Happy to TeamView if needed.

Stack trace:
   at xZune.Vlc.VlcMediaPlayer.set_Media(VlcMedia value) in C:\test\xZune.Vlc-master\xZune.VLC\VlcMediaPlayer.cs:line 529
   at xZune.Vlc.Wpf.VlcPlayer.LoadMedia(Uri uri) in C:\test\xZune.Vlc-master\xZune.VLC.WPF\VlcPlayer.cs:line 404
   at xZune.Vlc.Wpf.VlcPlayer.LoadMedia(String path) in C:\test\xZune.Vlc-master\xZune.VLC.WPF\VlcPlayer.cs:line 364
   at xZune.Vlc.Wpf.Sample.MainWindow.Load_Click(Object sender, RoutedEventArgs e) in C:\test\xZune.Vlc-master\xZune.VLC.WPF.Sample\MainWindow.xaml.cs:line 52
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at xZune.Vlc.Wpf.Sample.App.Main() in C:\test\xZune.Vlc-master\xZune.VLC.WPF.Sample\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Evilpaule** [comment]
My situation is a little bit complex. I use the whole thing as a plugin in an application. I load all dll via reflection and as i want to use the vlc plugin i drag and drop the control on a canvas. As i do this i get the error. I was too busy for include the whole project in my application to debug this. 
I hope i can do this soon..

**Comment by higankanshi** [comment]
But you don't give me your stack track information, I don't know what is wrong.
Every exception has stack track information.

**Comment by Evilpaule** [comment]
I want to give you the stack trace information but as you see in the picture i gave you, there is no chance to see the details where the stack trace infos are. The only chance for me is to include your project in mine so i can detect the nullpointer.

**Comment by higankanshi** [comment]
Ummm you can click the "Copy exception detail to clipboard" in exception window.
Then you can get all information of exception, you can give me it.

**Comment by gen3ric** [comment]
@higankanshi I get this same issue. The call stack is shallow, not sure if this helps. 

`System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in xZune.Vlc.Wpf.dll`

`Additional information: Object reference not set to an instance of an object.`

`at xZune.Vlc.Wpf.VlcPlayer.VideoFormatCallback(IntPtr& opaque, UInt32& chroma, UInt32& width, UInt32& height, UInt32& pitches, UInt32& lines)`

**Comment by higankanshi** [comment]
@gen3ric 
How do you use VlcPlayer?
XAML? or CS code?
If you want use VlcPlayer in CS code, please read this wiki [Use VlcPlayer with other controls](https://github.com/higankanshi/xZune.Vlc/wiki/Use-VlcPlayer-with-other-controls).

**Comment by gen3ric** [comment]
@higankanshi  Oh, thank you -- to be honest I didn't even consider looking at the Wiki tab because I've never seen a repo utilize it. So, thank you for doing that. I'll read up and try to see if that helps.

**Comment by Divaite** [comment]
Unfortunately sometimes we have the same exception, from the same line. Really hard for me to catch, but happens our testers got it.
Player is created using xaml, OS is different.

**Comment by philkild** [comment]
I am using this in AvalonDock and the problem is that when you undock/redock the vlc control, the Unloaded method on ThreadSeparatedControlHost is called.  This then means that the SeparateThreadDispatcher is null.  Could you please change the OnInitialised method in ThreadSeparatedControlHost to the following:

`protected override void OnInitialized(EventArgs e)
{
    Loaded += (sender, args) => LoadThreadSeparatedControl();
    Unloaded += (sender, args) => { UnloadThreadSeparatedControl(); };
    base.OnInitialized(e);
}`

Sorry, I can't get the code formatted properly but basically ensure LoadThreadSeparatedControl(); is called in the Loaded event and not just under initialisation.

**Comment by higankanshi** [comment]
Thanks for your contributions , In last commit we have add it to Meta.Vlc, now you can unload a VlcPlayer and reload VlcPlayer, it will work fine.

**Comment by abdul2000** [comment]
I think your recent changes broke the Stretch Feature! I cannot get the VlcPlayer to stretch anymore.

**Comment by abdul2000** [comment]
I figured it out. You need to call LoadThreadSeparatedControl() when initialising as well

        protected override void OnInitialized(EventArgs e)
        {
            LoadThreadSeparatedControl();
            Loaded += (sender, args) => { LoadThreadSeparatedControl(); };
            Unloaded += (sender, args) => { UnloadThreadSeparatedControl(); };

            base.OnInitialized(e);
        }

**Comment by higankanshi** [comment]
@abdul2000 this code have been add to Meta.Vlc, I will release it later.
