### ISSUE TITLE
InvalidOperationException when trying to play video

### ISSUE THREAD

**Issue by fpbooth** [higankanshi/Meta.Vlc#170]
Running: .net 4.5 / win 7 / x86
Problem: Using WPF and trying to display a local video I get the following exception trace: 

System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Meta.Vlc.Wpf.ThreadSeparatedImage.<>c__DisplayClass15_0.<set_Source>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Meta.Vlc.Wpf.ThreadSeparatedImage.set_Source(ImageSource value)
   at Meta.Vlc.Wpf.VlcPlayer.set_VideoSource(BitmapSource value)
   at Meta.Vlc.Wpf.VlcPlayer.VideoLockCallback(IntPtr opaque, IntPtr& planes)

Any idea what I am doing wrong? I just have a window and on loading the window I do  
```
if( vidControl.VlcMediaPlayer == null )
                    vidControl.Initialize( vidControl.LibVlcPath ); 
                    vidControl.LoadMedia(new Uri( item.Path, UriKind.RelativeOrAbsolute )); 
                    vidControl.Play();
```

**Comment by higankanshi** [comment]
See this wiki
https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls
