### ISSUE TITLE
Can't load LibVlc dlls

### ISSUE THREAD

**Issue by Nekonyx** [higankanshi/Meta.Vlc#172]
The application "falls" every time when I open the form with VlcPlayer.

```
System.Windows.Markup.XamlParseException occurred
  HResult=0x80131501
  Message='Initialization of 'Meta.Vlc.Wpf.VlcPlayer' threw an exception.' Line number '61' and line position '93'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at Anidub_App.Forms.ShowAnime.InitializeComponent() in D:\Projects\Anidub-App\Anidub App\Forms\ShowAnime.xaml:line 1

Inner Exception 1:
LibVlcLoadLibraryException: Can't load LibVlc dlls, check the platform and LibVlc target platform (should be same, x86 or x64).

Inner Exception 2:
Win32Exception: 无法载入指定的模块.
```

In AssemblyInfo.cs:
```csharp
[assembly: VlcSettings(@"..\..\LibVlc", "--no-video-title", "--no-sub-autodetect-file")]
````
Also I tried to set a full path, but received the same error

**Comment by higankanshi** [comment]
Check your vlc path, and version

> Can't load LibVlc dlls, check the platform and LibVlc target platform (should be same, x86 or x64).

**Comment by Nekonyx** [comment]
2.2.0.0
![default](https://cloud.githubusercontent.com/assets/16444061/21566170/7c395122-ceca-11e6-8361-9b8f260985d8.png)

**Comment by higankanshi** [comment]
Try change your project to x86
