### ISSUE TITLE
Random crashes upon loading/playing video

### ISSUE THREAD

**Issue by DannyGlover** [higankanshi/Meta.Vlc#196]
Hey guys.

I'm having a problem with random crashes when load/play is called:

`System.InvalidOperationException occurred
  HResult=0x80131509
  Message=The calling thread cannot access this object because a different thread owns it.
  Source=WindowsBase
  StackTrace:
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Meta.Vlc.Wpf.ThreadSeparatedImage.<>c__DisplayClass15_0.<set_Source>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Meta.Vlc.Wpf.ThreadSeparatedImage.set_Source(ImageSource value)
   at Meta.Vlc.Wpf.VlcPlayer.set_VideoSource(BitmapSource value)
   at Meta.Vlc.Wpf.VlcPlayer.VideoLockCallback(IntPtr opaque, IntPtr& planes)
`

Running it via a dispatcher doesn't seem to fix the issue. Has anyone else experienced this?

For reference, i'm playing local mp4 video files. 

Thank you

**Comment by timevision** [comment]
Having this problem as well. The issue shows up even with with the latest commit unmodified code.

- Just run the cleanly built "Meta.Vlc.Wpf.Sample.exe" .Net 4.5
- Use the Load button to play video files.
- Close the application with the Exit button and repeat the process.

at least 1 out of 5 times, the video will not show up, only Audio plays. I suspect something is not initialized correctly or there is still a race condition somewhere.

The problem shows up even more easily, if you create a new project and put the LoadMedia and Play method in the MainWindow method and run them immediately on startup, like so. Then the video almost does not show up half of the time.

What's the best way to ensure the VlcPlayer plays the video? Or at least make sure the Player is properly initialized before attempting to play?


    public partial class MainWindow : Window
    {

        VlcPlayer Player = null;

        public MainWindow()
        {
            InitializeComponent();

            Player = new VlcPlayer();
            MainGrid.Children.Add(Player);

            Player.Stop();
            Player.LoadMedia(@"C:\Users\FYonD\Desktop\Data\DemoVideos\AD2.mp4");
            Player.Play();

**Comment by timevision** [comment]
Oh I can communicate in Chinese as well, Higan, if I can help in anyway please let me know.
有什么能帮忙测试或者其他的事请尽管提。很愿意帮忙！谢啦。

**Comment by flawiddsouza** [comment]
I'm getting the same issue. Any update?

**Comment by darkLightx** [comment]
i have same problem,wainting for update
