### ISSUE TITLE
NullReferenceException at VlcPlayer.LoadMedia(Uri uri)

### ISSUE THREAD

**Issue by nadouamanda** [higankanshi/Meta.Vlc#253]
Can't be reproduced constantly. Wondering what can cause this issue. Below is the stack trace:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Meta.Vlc.Wpf.VlcPlayer.LoadMedia(Uri uri)
   at Meta.Vlc.Wpf.VlcPlayer.LoadMedia(String path)
   at App.Pages.Shared.LoginPopupPageBase.OnLoaded(Object sender, RoutedEventArgs routedEventArgs) in C:\Users\Amanda\Documents\repos\MyProject.App\Pages\Shared\LoginPopupPageBase.cs:line 80
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nadouamanda** [comment]
I'm initializing and loading the media inside the Page.Onloaded event, could this be the reason why?

**Comment by higankanshi** [comment]
I think you should load media after VlcPlay control be ready, you can try control media with a button...

**Comment by nadouamanda** [comment]
Is there an event I could subscribe to, to know that the vlcPlayer is ready?
