### ISSUE TITLE
Object Reference not set to an instance of an Object

### ISSUE THREAD

**Issue by nickkeane** [higankanshi/Meta.Vlc#295]
Object reference not set to an instance of an object.

App:     LaunchBox
Version: 13.18
Theme:   Neon Deluxe Arcade LB
Type:    System.NullReferenceException
Site:    Void <set_Source>b__0()
Source:  Meta.Vlc

   at Meta.Vlc.Wpf.ThreadSeparatedImage.<>c__DisplayClass27_0.<set_Source>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Meta.Vlc.Wpf.ThreadSeparatedImage.set_Source(ImageSource value)
   at Meta.Vlc.Wpf.VlcPlayer.set_VideoSource(BitmapSource value)
   at Meta.Vlc.Wpf.VlcPlayer.VideoLockCallback(Void* opaque, Void** planes)

Recent Log:

   12:32:40 PM Exception

**Comment by nickkeane** [comment]
https://bitbucket.org/jasondavidcarr/launchbox/issues/9566/object-reference-not-set-to-an-instance-of
